"""
Deeper Insights: Composite RS vs 63d
=====================================
Analyzes the trade log generated by DNA3 Composite comparison.
Looks for secondary insights regarding hit rates by sector,
average drawdowns per trade, and win streaks.
"""

import pandas as pd
import numpy as np
import warnings
import os
from collections import defaultdict
import json

warnings.filterwarnings('ignore')

DIR = "analysis_2026"

def get_sector(ticker):
    from utils.nifty500_list import SECTOR_MAP
    return SECTOR_MAP.get(ticker, 'Unknown')

def analyze_trades():
    print("=" * 80)
    print("DEEP TRADE INSIGHTS: COMPOSITE vs 63-DAY")
    print("=" * 80)
    
    # We will need to re-run a portion of the engine to get raw trade logs
    # if they weren't saved with all columns (regime, sector, etc.)
    # For now, let's load the trades summary we have, and also extract
    # insights from the equity curves directly if trades are missing details.
    
    # Let's run a quick 3-year slice of the engine just to extract detailed trade logs
    # for a deep dive.
    from dna3_composite_rs_comparison import Engine, fetch_data, INITIAL_CAPITAL
    from datetime import datetime, timedelta
    
    nifty, dc = fetch_data()
    if nifty is None or nifty.empty: return
    
    # Run 5 years to get a good sample of trades
    start = (datetime.now() - timedelta(days=365 * 5)).strftime('%Y-%m-%d')
    end = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
    
    si = nifty.index.searchsorted(start)
    ei = nifty.index.searchsorted(end)
    actual_start = nifty.index[si]
    actual_end = nifty.index[-1]
    
    print(f"\nRunning 5Y diagnostic block for detailed trade logs...")
    e_63d = Engine('V2.1-63d', 'v21', use_composite=False)
    e_comp = Engine('V2.1-Comp', 'v21', use_composite=True)
    
    e_63d.run(dc, nifty, actual_start, actual_end)
    e_comp.run(dc, nifty, actual_start, actual_end)
    
    print("\n[1] SECTOR ROTATION EFFICIENCY")
    print("-" * 80)
    
    def analyze_sectors(trade_log):
        sectors = defaultdict(list)
        for t in trade_log:
            if 'PnL%' in t:
                sec = get_sector(t['Ticker'])
                sectors[sec].append(t['PnL%'])
        
        stats = []
        for sec, pnls in sectors.items():
            if len(pnls) >= 5:  # Minimum 5 trades
                wins = sum(1 for p in pnls if p > 0)
                wr = wins / len(pnls) * 100
                stats.append({
                    'Sector': sec,
                    'Trades': len(pnls),
                    'WinRate': wr,
                    'AvgPnL': np.mean(pnls)
                })
        return pd.DataFrame(stats).sort_values('AvgPnL', ascending=False)
        
    s_63d = analyze_sectors(e_63d.trade_log)
    s_comp = analyze_sectors(e_comp.trade_log)
    
    print("Top 5 Sectors for 63-Day RS (by Avg PnL%):")
    if not s_63d.empty:
        for _, r in s_63d.head(5).iterrows():
            print(f"  {r['Sector']:<30} {r['Trades']:>3} trades | WinRate: {r['WinRate']:>4.0f}% | AvgPnL: {r['AvgPnL']:>5.1f}%")
            
    print("\nTop 5 Sectors for Composite RS (by Avg PnL%):")
    if not s_comp.empty:
        for _, r in s_comp.head(5).iterrows():
            print(f"  {r['Sector']:<30} {r['Trades']:>3} trades | WinRate: {r['WinRate']:>4.0f}% | AvgPnL: {r['AvgPnL']:>5.1f}%")
            
    print("\n[2] DRAWDOWN TIMING (Did Composite catch the bottom faster?)")
    print("-" * 80)
    
    # Calculate daily equity difference
    eq_63d = pd.DataFrame(e_63d.history).set_index('date')['equity']
    eq_comp = pd.DataFrame(e_comp.history).set_index('date')['equity']
    
    # Find the deepest drawdown in the 5Y period for Nifty
    nifty_eq = nifty.loc[actual_start:]['Close']
    pk = nifty_eq.cummax()
    dd = (nifty_eq - pk) / pk
    worst_idx = dd.idxmin()
    recovery_idx = dd[worst_idx:].idxmax() # Rough approx of recovery
    
    if not pd.isna(worst_idx):
        print(f"Major Market Bottom: {worst_idx.strftime('%Y-%m-%d')} (Max DD: {dd.min():.1%})")
        
        # Look 1 month before and 3 months after the bottom
        b_start = worst_idx - timedelta(days=30)
        b_end = worst_idx + timedelta(days=90)
        
        # Returns during recovery phase
        if b_start in eq_63d.index and b_end in eq_63d.index:
            r_63d = (eq_63d.loc[b_end] / eq_63d.loc[b_start] - 1) * 100
            r_comp = (eq_comp.loc[b_end] / eq_comp.loc[b_start] - 1) * 100
            
            print(f"Recovery Bounce (1mo before bottom -> 3mo after bottom):")
            print(f"  63d RS    : {r_63d:+.1f}%")
            print(f"  Composite : {r_comp:+.1f}%")
            if r_comp > r_63d:
                print("  -> Composite rotated into new leaders faster.")
            else:
                print("  -> 63d held better relative strength.")
                
    print("\n[3] HOLD TIME DISTRIBUTION (Does Composite overtrade?)")
    print("-" * 80)
    
    h_63d = [t['Hold_Days'] for t in e_63d.trade_log if 'Hold_Days' in t]
    h_comp = [t['Hold_Days'] for t in e_comp.trade_log if 'Hold_Days' in t]
    
    if h_63d and h_comp:
        print(f"  Under 10 Days (Whipsaws) : 63d={sum(1 for h in h_63d if h < 10)/len(h_63d):.1%} | Comp={sum(1 for h in h_comp if h < 10)/len(h_comp):.1%}")
        print(f"  10 - 30 Days             : 63d={sum(1 for h in h_63d if 10 <= h <= 30)/len(h_63d):.1%} | Comp={sum(1 for h in h_comp if 10 <= h <= 30)/len(h_comp):.1%}")
        print(f"  30 - 90 Days (Core Swing): 63d={sum(1 for h in h_63d if 30 < h <= 90)/len(h_63d):.1%} | Comp={sum(1 for h in h_comp if 30 < h <= 90)/len(h_comp):.1%}")
        print(f"  Over 90 Days (Runners)   : 63d={sum(1 for h in h_63d if h > 90)/len(h_63d):.1%} | Comp={sum(1 for h in h_comp if h > 90)/len(h_comp):.1%}")
        
    print("\n[4] CHRONIC LOSERS")
    print("-" * 80)
    def top_losers(log):
        fails = defaultdict(int)
        for t in log:
            if 'PnL%' in t and t['PnL%'] < 0:
                fails[t['Ticker']] += 1
        return sorted(fails.items(), key=lambda x: x[1], reverse=True)[:5]
        
    print(f"Top 5 most frequent losing tickers:")
    print(f"  63d RS    : {top_losers(e_63d.trade_log)}")
    print(f"  Composite : {top_losers(e_comp.trade_log)}")

if __name__ == "__main__":
    analyze_trades()
