"""
DNA3-V2.1 MORNING ALERT SYSTEM
================================
Sends a daily portfolio summary via Telegram + Email every morning.

Usage:
  python dna3_morning_alert.py          # Run once (send alert now)
  
Schedule via Windows Task Scheduler at 8:30 AM IST for automatic daily alerts.
"""

import json
import os
import sys
from datetime import datetime

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

SNAPSHOT_FILE = "data/dna3_portfolio_snapshot.json"
TRADE_LOG_FILE = "data/dna3_trade_log.csv"
EQUITY_CURVE_FILE = "data/dna3_equity_curve.csv"


def load_portfolio():
    """Load latest DNA3 portfolio snapshot."""
    if not os.path.exists(SNAPSHOT_FILE):
        return None
    with open(SNAPSHOT_FILE, 'r') as f:
        return json.load(f)


def build_telegram_message(data):
    """Build a formatted Telegram message (HTML)."""
    date = data.get('date', 'Unknown')
    equity = data.get('equity', 0)
    cash = data.get('cash', 0)
    holdings = data.get('portfolio', [])
    count = data.get('count', 0)
    
    # CAGR calculation
    initial = 1000000
    start = datetime(2026, 2, 1)
    days = (datetime.now() - start).days
    if days > 0 and equity > 0:
        cagr = ((equity / initial) ** (365.25 / days) - 1) * 100
        total_ret = ((equity - initial) / initial) * 100
    else:
        cagr = 0
        total_ret = 0

    msg = f"<b>DNA3-V2.1 Morning Brief</b>\n"
    msg += f"<i>{date}</i>\n\n"
    msg += f"Portfolio: Rs {equity:,.0f}\n"
    msg += f"Return: {total_ret:+.1f}% | CAGR: {cagr:+.1f}%\n"
    msg += f"Holdings: {count} | Cash: Rs {cash:,.0f}\n"
    msg += f"\n<b>--- Holdings ---</b>\n"
    
    for h in holdings[:15]:
        ticker = h.get('Ticker', '').replace('.NS', '')
        pnl = h.get('PnL%', 0)
        price = h.get('Price', 0)
        rs = h.get('RS_Score', 0)
        icon = '+' if pnl >= 0 else ''
        msg += f"  {ticker}: Rs{price:.0f} ({icon}{pnl:.1f}%) RS:{rs}\n"
    
    # Recent trades from trade log
    if os.path.exists(TRADE_LOG_FILE):
        import pandas as pd
        try:
            trades = pd.read_csv(TRADE_LOG_FILE)
            recent = trades.tail(3)
            if not recent.empty:
                msg += f"\n<b>--- Recent Trades ---</b>\n"
                for _, t in recent.iterrows():
                    action = t.get('Action', '')
                    ticker = str(t.get('Ticker', '')).replace('.NS', '')
                    pnl = t.get('PnL%', 0)
                    msg += f"  {action} {ticker} ({pnl:+.1f}%)\n"
        except:
            pass
    
    msg += f"\n<i>Auto-generated by Alpha Trend Dashboard</i>"
    return msg


def build_email_html(data):
    """Build a rich HTML email for the DNA3 morning report."""
    date = data.get('date', 'Unknown')
    equity = data.get('equity', 0)
    cash = data.get('cash', 0)
    holdings = data.get('portfolio', [])
    count = data.get('count', 0)
    
    initial = 1000000
    start = datetime(2026, 2, 1)
    days = (datetime.now() - start).days
    if days > 0 and equity > 0:
        cagr = ((equity / initial) ** (365.25 / days) - 1) * 100
        total_ret = ((equity - initial) / initial) * 100
    else:
        cagr = 0
        total_ret = 0
    
    ret_color = '#00C853' if total_ret >= 0 else '#FF5252'
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #0f0f23; color: #eee; padding: 20px; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #1a1a2e; border-radius: 16px; padding: 30px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 25px; border-radius: 12px; text-align: center; margin-bottom: 25px; }}
            .header h1 {{ margin: 0; color: white; font-size: 22px; }}
            .header p {{ margin: 8px 0 0 0; color: rgba(255,255,255,0.8); font-size: 14px; }}
            .stats {{ display: flex; justify-content: space-around; margin-bottom: 25px; }}
            .stat-box {{ text-align: center; background: rgba(255,255,255,0.05); padding: 15px 10px; border-radius: 10px; flex: 1; margin: 0 4px; }}
            .stat-value {{ font-size: 22px; font-weight: bold; }}
            .stat-label {{ font-size: 11px; color: #888; margin-top: 5px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
            th {{ text-align: left; padding: 8px; color: #888; font-size: 12px; border-bottom: 1px solid rgba(255,255,255,0.1); }}
            td {{ padding: 8px; font-size: 13px; border-bottom: 1px solid rgba(255,255,255,0.05); }}
            .positive {{ color: #00C853; }}
            .negative {{ color: #FF5252; }}
            .footer {{ text-align: center; font-size: 11px; color: #555; margin-top: 25px; padding-top: 15px; border-top: 1px solid rgba(255,255,255,0.1); }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>DNA3-V2.1 Morning Brief</h1>
                <p>{date}</p>
            </div>
            
            <div class="stats">
                <div class="stat-box">
                    <div class="stat-value" style="color:{ret_color}">{total_ret:+.1f}%</div>
                    <div class="stat-label">TOTAL RETURN</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value" style="color:#667eea">Rs {equity:,.0f}</div>
                    <div class="stat-label">PORTFOLIO VALUE</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">{count}</div>
                    <div class="stat-label">HOLDINGS</div>
                </div>
            </div>
            
            <table>
                <tr><th>Stock</th><th>Price</th><th>P&L</th><th>RS</th></tr>
    """
    
    for h in holdings[:15]:
        ticker = h.get('Ticker', '').replace('.NS', '')
        price = h.get('Price', 0)
        pnl = h.get('PnL%', 0)
        rs = h.get('RS_Score', 0)
        pnl_class = 'positive' if pnl >= 0 else 'negative'
        html += f"""
                <tr>
                    <td><strong>{ticker}</strong></td>
                    <td>Rs {price:,.0f}</td>
                    <td class="{pnl_class}">{pnl:+.1f}%</td>
                    <td>{rs:.1f}</td>
                </tr>
        """
    
    html += f"""
            </table>
            
            <div class="footer">
                Auto-generated by Alpha Trend Dashboard | CAGR: {cagr:+.1f}%
            </div>
        </div>
    </body>
    </html>
    """
    return html


def send_morning_alert():
    """Main function: Load portfolio and send via Telegram + Email."""
    data = load_portfolio()
    if not data:
        print("No portfolio snapshot found. Run dna3_current_portfolio.py first.")
        return False
    
    results = {}
    
    # 1. TELEGRAM
    try:
        from utils.telegram_notifier import send_telegram_message, is_telegram_configured
        if is_telegram_configured():
            msg = build_telegram_message(data)
            success, resp = send_telegram_message(msg)
            results['telegram'] = success
            print(f"Telegram: {'Sent' if success else 'Failed'} - {resp}")
        else:
            print("Telegram: Not configured. Skipping.")
            results['telegram'] = False
    except Exception as e:
        print(f"Telegram Error: {e}")
        results['telegram'] = False
    
    # 2. EMAIL
    try:
        from utils.email_notifier import _send_email, is_email_configured
        if is_email_configured():
            html = build_email_html(data)
            subject = f"DNA3 Morning Brief - {data.get('date', datetime.now().strftime('%Y-%m-%d'))}"
            success, resp = _send_email(subject, html)
            results['email'] = success
            print(f"Email: {'Sent' if success else 'Failed'} - {resp}")
        else:
            print("Email: Not configured. Skipping.")
            results['email'] = False
    except Exception as e:
        print(f"Email Error: {e}")
        results['email'] = False
    
    return results


if __name__ == "__main__":
    print(f"[{datetime.now()}] DNA3 Morning Alert System")
    print("=" * 50)
    send_morning_alert()
