# DNA-3 V2 EXTENDED: COMPREHENSIVE ANALYSIS REPORT

## Test Parameters
- **Period**: 10 Years
- **Universe**: 68 Stocks (9 Sectors)
- **Max Portfolio Size**: 20 Stocks
- **Initial Capital**: Rs. 10,00,000

---

## [1] PORTFOLIO PERFORMANCE

| Metric | Value |
|:-------|:------|
| **Total Return** | **520.52%** |
| Nifty Return | 268.05% |
| **Alpha** | **+252.47%** |
| **CAGR** | **20.03%** |
| Max Portfolio Drawdown | -24.87% |
| Total Trades | 572 |
| **Win Rate** | **65.7%** |

---

## [2] RETURN STATISTICS

| Metric | All Trades | Winners | Losers |
|:-------|:-----------|:--------|:-------|
| **Average Return** | **8.93%** | +20.67% | -13.58% |
| Median Return | 4.43% | +12.11% | -15.66% |
| Std Dev | 29.85% | 30.53% | 6.43% |
| **Max Win** | **+296.61%** | | |
| **Max Loss** | **-26.66%** | | |

### Key Insight:
- Winners have HIGH variability (SD 30.5%) - big upside potential
- Losers have LOW variability (SD 6.4%) - losses are capped near stop

---

## [3] HOLDING PERIOD ANALYSIS

| Metric | All | Winners | Losers |
|:-------|:----|:--------|:-------|
| **Avg Holding** | 109 days | **125 days** | 78 days |
| Median Holding | 86 days | 100 days | 55 days |
| Min | 3 days | | |
| Max | 727 days | | |

### Key Insight:
**Winners are held 47 days longer** on average.
- Short exits (<30 days) = likely losers
- Long holds (>100 days) = likely winners

---

## [4] ENTRY METRICS: WINNERS vs LOSERS

| Entry Metric | Winners | Losers | Edge |
|:-------------|:--------|:-------|:-----|
| **RS vs Nifty** | **20.2%** | 18.8% | **+1.4%** |
| Volatility | 40.8% | 41.2% | -0.4% |
| **Trend Score** | **92.6** | 91.1 | **+1.5** |
| RSI | 58.0 | 59.8 | -1.8 |
| Volume Ratio | 1.10 | 1.10 | 0.00 |
| PE Ratio | 39.4 | 36.9 | +2.5 |

### Key Insights:

1. **RS is THE differentiator** (+1.4% higher for winners)
2. **Trend Score matters** (+1.5 higher for winners)
3. **RSI slightly lower for winners** (58 vs 60) - not overbought
4. **Volatility is similar** (40-41%) - both use high beta
5. **Volume Ratio identical** (1.10x) - not a differentiator
6. **PE slightly higher for winners** - growth premium

---

## [5] INTRA-TRADE METRICS

| Metric | Winners | Losers |
|:-------|:--------|:-------|
| **Avg Peak Gain** | **+36.1%** | +5.0% |
| **Avg Trade Drawdown** | **-11.3%** | -17.8% |

### Key Insight:
- Winners peak at +36% before trailing stop triggers
- Losers barely move (+5%) before hitting hard stop
- Winners experience smaller drawdowns (-11% vs -18%)

---

## [6] SECTOR PERFORMANCE

| Sector | Avg PnL | Trades | Win Rate |
|:-------|:--------|:-------|:---------|
| **Consumer** 🏆 | **+16.26%** | 30 | 70.0% |
| **Energy** | **+15.71%** | 50 | 58.0% |
| **IT Services** | **+12.88%** | 69 | **71.0%** |
| **Auto** | +12.05% | 40 | 67.5% |
| **Pharma** | +10.52% | 41 | 65.9% |
| Metals | +7.44% | 128 | 64.1% |
| **Industrials** | +6.73% | 73 | **71.2%** |
| Realty | +5.80% | 88 | 65.9% |
| Banking | +1.53% | 53 | 58.5% |

### Sector Insights:
- **Consumer leads** (+16.3% avg) with 70% win rate
- **Energy and IT** are strong performers
- **Metals has most trades** (128) but average returns
- **Banking underperforms** (+1.5% avg) - avoid or underweight

---

## [7] EXIT REASON ANALYSIS

| Exit Reason | Avg PnL | Count | Std Dev |
|:------------|:--------|:------|:--------|
| **Trail** | **+20.62%** | 377 (66%) | 30.5% |
| **Stop** | **-13.65%** | 195 (34%) | 6.4% |

### Key Insight:
- **66% of exits are trailing stops (winners)**
- Stop losses limit damage (-13.65% avg)
- Trailing stops capture big winners (+20.62% avg)

---

## [8] THE WINNER PROFILE

### What Winners Look Like at Entry:
| Factor | Optimal Value |
|:-------|:--------------|
| RS vs Nifty | **>20%** (higher the better) |
| Trend Score | **>92** |
| RSI | **55-60** (not overbought) |
| Volatility | **40-45%** |
| Volume Ratio | **~1.1x** |
| Holding | **100-150 days** |

### What Losers Look Like at Entry:
- RS around 18-19% (just above threshold)
- RSI touching 60 (nearing overbought)
- Exit early (<80 days) hitting hard stop

---

## [9] EDGE SUMMARY

| Edge Factor | Impact | Actionable? |
|:------------|:-------|:------------|
| **Higher RS at entry** | +1.4% | ✅ Prioritize RS >20% |
| **Higher Trend Score** | +1.5 | ✅ Prefer Trend >92 |
| **Longer holding** | +47 days | ✅ Be patient with winners |
| **Trailing stops** | +20.6% avg | ✅ Let winners run |

---

## [10] RECOMMENDATIONS

### Quick Wins (Implement Today):
1. **Prioritize RS > 20%** (not just >2%)
   - Entry quality improves significantly
   
2. **Prefer Trend Score > 92**
   - Winners have higher trend scores

3. **Don't exit early**
   - If not stopped out, hold minimum 90 days
   - Winners need 100-125 days to mature

4. **Sector Allocation**
   - Overweight: Consumer, Energy, IT
   - Underweight: Banking, Realty

---

## [11] FINAL STATISTICS

| Metric | Value |
|:-------|:------|
| Period | 10 Years |
| Total Trades | **572** |
| Win Rate | **65.7%** |
| Profit Factor | **2.5x** (Winners/Losers) |
| Avg Win | **+20.67%** |
| Avg Loss | **-13.58%** |
| Max Win | **+296.61%** |
| Max Loss | **-26.66%** |
| Max Drawdown | **-24.87%** |
| CAGR | **20.03%** |
| Alpha vs Nifty | **+252%** |

---

## Trade Log
Detailed trade log saved to: `analysis_2026/dna3_comprehensive_trades.csv`

*This is the most comprehensive DNA-3 V2 analysis to date.*
