# DNA-3 V2 EXTENDED: SURGICAL ANALYSIS

## The Deep Dive Request
"Test across timeframes, regimes, find Achilles heel, what's different from pure momentum."

---

## [1] OVERALL PERFORMANCE (10 Years)

| Strategy | Total Return | CAGR |
|:---------|:-------------|:-----|
| **DNA-3 V2** | **370%** | **16.74%** |
| Pure Momentum | 367% | 16.66% |
| Nifty 50 | 268% | 13.93% |

> DNA-3 V2 beats both Pure Momentum and Nifty.

---

## [2] PERFORMANCE BY REGIME

| Regime | Avg PnL | Trades | Win Rate |
|:-------|:--------|:-------|:---------|
| **Strong Bear** | **10.7%** | 35 | **68.6%** |
| **Mild Bull** | **10.2%** | 113 | 65.5% |
| Recovery | 6.4% | 24 | 66.7% |
| Strong Bull | 4.8% | 145 | 62.8% |

### Insight:
- **Best time to trade DNA-3 V2:** Mild Bull and Strong Bear
- **Worst time:** Strong Bull (crowded, mean reversion kicks in)

---

## [3] ENTRY QUALITY ANALYSIS

### By Relative Strength at Entry:

| RS at Entry | Avg PnL | Trades | Win Rate |
|:------------|:--------|:-------|:---------|
| **2-5%** | **15.5%** | 34 | **70.6%** |
| 5-10% | -0.1% | 32 | 46.9% |
| 10-20% | 2.1% | 86 | 60.5% |
| **20-50%** | **10.4%** | 147 | **70.1%** |
| 50%+ | 7.2% | 18 | 61.1% |

### Key Discovery:
- **Sweet Spots:** RS 2-5% (early movers) and RS 20-50% (confirmed momentum)
- **Danger Zone:** RS 5-10% (false breakouts, 47% win rate)
- **Too Hot:** RS 50%+ starts to fade

### By Volatility at Entry:

| Volatility | Avg PnL | Trades | Win Rate |
|:-----------|:--------|:-------|:---------|
| **30-35%** | **8.7%** | 121 | 63.6% |
| 35-45% | 7.4% | 103 | 65.1% |
| 45-60% | 5.9% | 75 | 66.7% |
| 60%+ | 2.7% | 17 | 58.8% |

### Key Discovery:
- **Lower volatility (30-35%) produces better absolute returns**
- **Higher volatility (60%+) = lower returns, more noise**
- The "high beta wins" insight needs nuance: 30-45% is the goldilocks zone

---

## [4] EXIT ANALYSIS

| Exit Reason | Avg PnL | Count |
|:------------|:--------|:------|
| **Trail** | **+18.5%** | 206 |
| Stop | -13.0% | 111 |

### Key Discovery:
- **65% of exits are Trailing Stops (winners)**
- **35% are Hard Stops (losers)**
- Exit discipline is CRITICAL. Trailing stops capture the big winners.

---

## [5] HOLDING PERIOD ANALYSIS

| Holding Period | Avg PnL | Trades | Win Rate |
|:---------------|:--------|:-------|:---------|
| <30 days | -8.3% | 35 | 31.4% |
| 30-60 days | -0.3% | 82 | 61.0% |
| 60-120 days | 5.6% | 108 | 69.4% |
| **120-365 days** | **18.6%** | 85 | **72.9%** |
| **365+ days** | **71.6%** | 7 | **100.0%** |

### Key Discovery:
- **Short-term trades (<30 days) are disasters** (31% win rate)
- **Sweet spot: 60-365 days** (70%+ win rate)
- **Long-term holds (365+) have 100% win rate but rare**
- **DNA-3 V2 is NOT a swing trading strategy. It's a position trading strategy.**

---

## [6] DNA-3 V2 vs PURE MOMENTUM

| Metric | DNA-3 V2 | Pure Momentum |
|:-------|:---------|:--------------|
| Trades | 317 | 279 |
| Win Rate | **64.7%** | 62.7% |
| Avg PnL | 7.5% | 8.8% |

### What's Different:
1. **DNA-3 V2 has more trades** (more opportunities)
2. **DNA-3 V2 has higher win rate** (better filtering)
3. **Pure Momentum has higher avg PnL** (fewer, bigger bets)
4. **DNA-3 V2 adds RS + Volatility filters** which improve consistency

---

## [7] ACHILLES HEEL (Where DNA-3 Fails)

### Big Losers (>10% loss): 83 trades

| Factor | Value |
|:-------|:------|
| Most Common Regime | **Strong Bull** |
| Avg RS at Entry | 20.5% |
| Avg Volatility at Entry | 40.9% |

### The Weakness:
- **DNA-3 V2 fails in Strong Bull markets**
- High volatility (40.9%) + Strong Bull = Overbought conditions
- These entries catch the top of momentum runs
- **Solution:** Reduce position size or skip entries when in Strong Bull + Vol > 40%

---

## [8] THE SECRET SAUCE (What Makes DNA-3 V2 Work)

### Winner vs Loser Profile at Entry:

| Metric | Winners | Losers | Edge |
|:-------|:--------|:-------|:-----|
| Avg RS | 24.2% | 21.7% | +2.5% |
| Avg Volatility | 41.0% | 40.9% | ~Same |

### The 4 Pillars:

1. **RELATIVE STRENGTH FILTER**
   - Forces buying stocks outperforming Nifty
   - Winners have +2.5% higher RS at entry

2. **VOLATILITY FILTER**
   - 30%+ ensures room to move
   - But 30-45% is the goldilocks zone

3. **TREND FILTER (Price > MA50)**
   - Prevents buying falling knives
   - Confirms uptrend before entry

4. **EXIT DISCIPLINE**
   - Hard Stop -15%: Limits max loss (avg -13%)
   - Trailing Stop: Captures big wins (avg +18.5%)
   - 65% of exits are winners via trailing

---

## FINAL VERDICT

| What Works | What Fails |
|:-----------|:-----------|
| Mild Bull regime | Strong Bull regime |
| RS 2-5% or 20-50% | RS 5-10% (false breakouts) |
| Volatility 30-45% | Volatility 60%+ |
| Holding 60-365 days | Holding <30 days |
| Trailing exits | Early panic exits |

### DNA-3 V2 is a POSITION TRADING strategy for MILD BULL markets.
### Its Achilles Heel is STRONG BULL + HIGH VOLATILITY entries.

*Now you know EXACTLY when to trade it and when to sit out.*

